import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "yuyakun.io",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body className='bg-white'>
        {children}
      </body>
    </html>
  );
}
